### ISSUE TITLE
Mozilla Observatory doesn't scan folders

### ISSUE THREAD

**Issue by alinnow** [Jieiku/zola-themes#3]
Demo sites that use folders (e.g. those hosted on a Git forge's Pages instance) do not have the correct results returned by Mozilla Observatory as that only scans hosts, not URLs.

It might be worth considering removing it for sites without JavaScript, as the readme implies it's not of any use in that case.

(disclosure: I ported Bear blog theme to Zola and want to increase its score :)

**Comment by Jieiku** [comment]
Actually I host my own private instance of Mozilla Observatory, Yellow Lab Tools, and Lighthouse tools. I do this so that I do not hammer their servers. You are absolutely correct that NORMALLY Observatory will not let you scan a subdomain, however I modified Observatory to allow it. I would be happy to post the results here if you want. I can also outline the modifications I made to Observatory to allow it.

To up your score look at Abridge and Tabi, they have directives in config.toml that will help with your score. There is only so much you can do on github pages though because they do not allow server configuration like netlify does through their [netlify.toml file](https://github.com/Jieiku/abridge/blob/288de9dac39869ac94d0265351f5884a78dce5a8/netlify.toml#L11-L19).

or cloudflare pages [_headers file](https://github.com/Jieiku/abridge/blob/master/static/_headers).

As far as I know these are the only things you can configure, but you can also ensure your site does not have any mistakes, as those dock your score points too, for example inline styles or scripts, or not using resource integrity.
https://github.com/Jieiku/abridge/blob/288de9dac39869ac94d0265351f5884a78dce5a8/config.toml#L267-L280

**Comment by alinnow** [comment]
Ah, good to know that you host your own instance of MO. I think that it's good to know that, maybe it could be mentioned near the legends of the table headers? Might also explain why I got a different score from GL

I'm not really too concerned about the other scores and the headers, but I might actually move it to netlify and add a deploy button, since I know other people like that service :)

**Comment by Jieiku** [comment]
yeah, I have had zero complaints for free. I think for your demo site it certainly wont be an issue. For a real site with lots of traffic they may have bandwidth caps but I honestly have no idea.

I will add some info to the readme on the next commit. Going to leave this issue open for now. And yes YellowLabTools actually has a new version in the works: https://github.com/YellowLabTools/YellowLabTools/pull/386

I am using a version newer than the public instance, not the 3.0 version listed in the above comments, but newer than public, its been out a while. Additionally I do not use the GLOBAL score returned by yellow lab tools. I use an Average of all the category scores. Which is mentioned on the readme page, but probably easily overlooked. The average score makes more sense to use than the global score because it gives a more granular and accurate result, which is useful when trying to rank pages against one another. (before I switched from global score to category score I would say half of the zola themes hit 100/100, so it was more difficult to compare them)

**Comment by Jieiku** [comment]
I thought you said YL, but you actually said GL. for GL I add the category scores together then average them: https://pagespeed.web.dev/analysis/https-alanpearce-codeberg-page-zola-bearblog/z4j7y61qxf?form_factor=mobile

so (100+100+95+91)/4 which at pagespeed.web.dev does work out to lower than the score I have listed in my results, but I noticed pagespeed.web.dev actually includes a couple additional accessibility checks.

**Comment by alinnow** [comment]
I mis-remembered and edited, sorry! Yeah, it makes more sense your way. I would have expected the official site to use an average, as well.

P.S. https://observatory.mozilla.org/analyze/zola-bearblog.netlify.app :)

**Comment by Jieiku** [comment]
hey, you should remove frame-ancestors 'none';  from your CSP, apparently GL is flagging it. lol the rest should be fine. I just noticed when I used pagespeed insights. (will be removing frame-ancestors from abridge as well)

**Comment by Jieiku** [comment]
Nice job. I will do another scan this evening

**Comment by Jieiku** [comment]
If you are using netlify then I would actually just disable your META tags for the CSP and referrer.

**Comment by Jieiku** [comment]
Nice job. I will do another scan soon.

If you are using netlify then I would actually just disable your META tags for the CSP and referrer. (this is why they are commented out in abridge. because I use netlify)

Whenever I run my batch scripts, it pulls the info from the theme.toml file, so you will want to update the info there if you switch to netlify.

**Comment by alinnow** [comment]
I'll keep the meta tags there in case the end user isn't using netlify :)

Not everyone fully understands this stuff and I think it's nice to cater to them.

Thanks for the tip about the `theme.toml`, I knew I was missing something big 😁

**Comment by Jieiku** [comment]
I just updated the page, and can see you must have taken care of the GL stuff, Nice Job!
